export const GROUPS_UPLOAD = "GROUPS_UPLOAD";
export const GROUPS_UPLOAD_SUCCESS = "GROUPS_UPLOAD_SUCCESS";
export const GROUPS_UPLOAD_FAILURE = "GROUPS_UPLOAD_FAILURE";

export const GET_GROUPS = "GET_GROUPS";
export const GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS";
export const GET_GROUPS_FAILURE = "GET_GROUPS_FAILURE";

export const COMPANIES_DETAILS = "COMPANIES_DETAILS";
export const COMPANIES_DETAILS_SUCCESS = "COMPANIES_DETAILS_SUCCESS";
export const COMPANIES_DETAILS_FAILURE = "COMPANIES_DETAILS_FAILURE";

export const UPLOAD_DOCS = "UPLOAD_DOCS";
export const UPLOAD_DOCS_SUCCESS = "UPLOAD_DOCS_SUCCESS";
export const UPLOAD_DOCS_FAILURE = "UPLOAD_DOCS_FAILURE";

export const GROUPS_SUBCATEGORIES = "GROUPS_SUBCATEGORIES";
export const GROUPS_SUBCATEGORIES_SUCCESS = "GROUPS_SUBCATEGORIES_SUCCESS";
export const GROUPS_SUBCATEGORIES_FAILURE = "GROUPS_SUBCATEGORIES_FAILURE";

export const SAVE_COMMUNICATION = "SAVE_COMMUNICATION";
export const SAVE_COMMUNICATION_SUCCESS = "SAVE_COMMUNICATION_SUCCESS";
export const SAVE_COMMUNICATION_FAILURE = "SAVE_COMMUNICATION_FAILURE";

export const GET_COMMUNICATION = "GET_COMMUNICATION";
export const GET_COMMUNICATION_SUCCESS = "GET_COMMUNICATION_SUCCESS";
export const GET_COMMUNICATION_FAILURE = "GET_COMMUNICATION_FAILURE";

export const GET_COUNTIES = "GET_COUNTIES";
export const GET_COUNTIES_SUCCESS = "GET_COUNTIES_SUCCESS";
export const GET_COUNTIES_FAILURE = "GET_COUNTIES_FAILURE";

export const GET_CITES = "GET_CITES";
export const GET_CITES_SUCCESS = "GET_CITES_SUCCESS";
export const GET_CITES_FAILURE = "GET_CITES_FAILURE";

export const UPLOAD_TRAINING = "UPLOAD_TRAINING";
export const UPLOAD_TRAINING_SUCCESS = "UPLOAD_TRAINING_SUCESSS";
export const UPLOAD_TRAINING_FAILURE = "UPLOAD_TRAINING_FAILURE";

export const UPLOAD_PROPERTY = "UPLOAD_PROPERTY";
export const UPLOAD_PROPERTY_SUCCESS = "UPLOAD_PROPERTY_SUCESSS";
export const UPLOAD_PROPERTY_FAILURE = "UPLOAD_PROPERTY_FAILURE";
