export const marketPlaceData = [
  {
    infoName: "Job Opening",
    infoID: "#20183",
    tags: true,
    title: "Property Inspector",
    btnText: "Apply",
    statusText: "Training Available",
    join: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-primary",
  },
  {
    infoName: "Job Opening",
    infoID: "#20184",
    tags: true,
    title: "Property Handler",
    btnText: "Apply",
    statusText: "Training Available",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-primary",
  },
  {
    infoName: "Job Opening",
    infoID: "#20185",
    tags: true,
    title: "Business Handler",
    btnText: "Apply",
    statusText: "Training Available",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-primary",
  },
  {
    infoName: "Job Opening",
    infoID: "#20186",
    tags: true,
    title: "Job Handler",
    btnText: "Apply",
    statusText: "Training Available",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-primary",
  },
  {
    infoName: "Job Opening",
    infoID: "#20187",
    tags: true,
    title: "Trader",
    btnText: "Apply",
    statusText: "Training Available",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-primary",
  },
  {
    infoName: "Job Opening",
    infoID: "#20188",
    tags: true,
    title: "Trading Handler",
    btnText: "Apply",
    statusText: "Training Available",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-primary",
  },
  {
    infoName: "Job Opening",
    infoID: "#20189",
    tags: true,
    title: "Stock Handler",
    btnText: "Apply",
    statusText: "Training Available",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-primary",
  },
  {
    infoName: "Job Opening",
    infoID: "#201810",
    tags: true,
    title: "Stock Broker",
    btnText: "Apply",
    statusText: "Training Available",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",

    tagColor: "has-background-primary",
  },
];

export const trainingDataPlace = [
  {
    infoName: "Training",
    infoID: "#20183",
    tags: true,
    title: "Property Inspector",
    btnText: "Start Training",
    statusText: "Archive",
    join: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-warning",
  },
  {
    infoName: "Training",
    infoID: "#20184",
    tags: true,
    title: "Property Handler",
    btnText: "Start Training",
    statusText: "Archive",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-warning",
  },
  {
    infoName: "Training",
    infoID: "#20185",
    tags: true,
    title: "Business Handler",
    btnText: "Start Training",
    statusText: "Archive",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-warning",
  },
  {
    infoName: "Training",
    infoID: "#20186",
    tags: true,
    title: "Job Handler",
    btnText: "Start Training",
    statusText: "Archive",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-warning",
  },
  {
    infoName: "Training",
    infoID: "#20187",
    tags: true,
    title: "Trader",
    btnText: "Start Training",
    statusText: "Archive",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-warning",
  },
  {
    infoName: "Training",
    infoID: "#20188",
    tags: true,
    title: "Trading Handler",
    btnText: "Apply",
    statusText: "Archive",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-warning",
  },
  {
    infoName: "Training",
    infoID: "#20189",
    tags: true,
    title: "Stock Handler",
    btnText: "Apply",
    statusText: "Training Available",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-warning",
  },
  {
    infoName: "Training",
    infoID: "#201810",
    tags: true,
    title: "Stock Broker",
    btnText: "Apply",
    statusText: "Training Available",
    join: false,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
    tagColor: "has-background-warning",
  },
];
