export const trainingCardData = [
  {
    infoName: "Training",
    infoID: "#20183",
    training: true,
    title: "Customer Service Training 101",
    btnText: "Edit",
    statusText: "Delete",
    join: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
  },
  {
    infoName: "Training",
    infoID: "#20184",
    training: true,
    title: "Customer Service Training 101",
    btnText: "Start Training",
    statusText: "Archive",
    join: true,
    startTraining: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
  },
  {
    infoName: "Training",
    infoID: "#20185",
    training: true,
    title: "Customer Service Training 101",
    btnText: "Start Training",
    statusText: "Archive",
    join: true,
    startTraining: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
  },
  {
    infoName: "Training",
    infoID: "#20186",
    training: true,
    title: "Customer Service Training 101",
    btnText: "Start Training",
    statusText: "Archive",
    join: true,
    startTraining: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
  },
  {
    infoName: "Training",
    infoID: "#20187",
    training: true,
    title: "Customer Service Training 101",
    btnText: "Start Training",
    statusText: "Archive",
    join: true,
    startTraining: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
  },
  {
    infoName: "Training",
    infoID: "#20188",
    training: true,
    title: "Customer Service Training 101",
    btnText: "Start Training",
    statusText: "Archive",
    join: true,
    startTraining: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
  },
  {
    infoName: "Training",
    infoID: "#20189",
    training: true,
    title: "Customer Service Training 101",
    btnText: "Start Training",
    statusText: "Archive",
    join: true,
    startTraining: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
  },
  {
    infoName: "Training",
    infoID: "#201810",
    training: true,
    title: "Customer Service Training 101",
    btnText: "Start Training",
    statusText: "Archive",
    join: true,
    startTraining: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
  },
  {
    infoName: "Training",
    infoID: "#201811",
    training: true,
    title: "Customer Service Training 101",
    btnText: "Start Training",
    statusText: "Archive",
    join: true,
    startTraining: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
  },
  {
    infoName: "Training",
    infoID: "#201812",
    training: true,
    title: "Customer Service Training 101",
    btnText: "Start Training",
    statusText: "Archive",
    join: true,
    startTraining: true,
    availableText: "Available via",
    availableSource: "THE MARKETPLACE",
  },
];
